volumes:
  n8n_storage:
    driver: local
    driver_opts:
      type: none
      device: ${N8N_VOL}
      o: bind
  ollama_storage:
    driver: local
    driver_opts:
      type: none
      device: ${OLLAMA_VOL}
      o: bind
  ollama_code:
    driver: local
    driver_opts:
      type: none
      device: ${OLLAMA_CODE_VOL}
      o: bind
  ollama_webui_data:
    driver: local
    driver_opts:
      type: none
      device: ${OLLAMA_WEB_VOL}
      o: bind

services:
  n8n-container:
    image: n8nio/n8n:latest
    ports:
      - "5678:5678"
    volumes:
      - n8n_storage:/home/node/.n8n
    environment:
      - N8N_DIAGNOSTICS_ENABLED=false
      - N8N_RUNNERS_ENABLED=true
      - WEBHOOK_URL=${WEBHOOK_URL}

  ollama:
    image: docker.io/ollama/ollama:latest
    ports:
      - 11434:11434
    volumes:
      - ollama_code:/code
      - ollama_storage:/root/.ollama
    container_name: ollama
    pull_policy: always
    tty: true
    restart: always
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      - OLLAMA_KEEP_ALIVE=24h
      - OLLAMA_HOST=0.0.0.0
    networks:
      - ollama-docker

  ollama-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: ollama-webui
    volumes:
      - ollama_webui_data:/app/backend/data
    depends_on:
      - ollama
    ports:
      - 8080:8080
    environment: # https://docs.openwebui.com/getting-started/env-configuration#default_models
      - OLLAMA_BASE_URLS=http://host.docker.internal:11434 #comma separated ollama hosts
      - ENV=dev
      - WEBUI_AUTH=False
      - WEBUI_NAME=Jeff Ollama Chatbot
      - WEBUI_DESCRIPTION=Ollama Chatbot
      - WEBUI_URL=http://localhost:8080
      - WEBUI_SECRET_KEY=penangHokkienMeeIsNOTprawnNoodles
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped
    networks:
      - ollama-docker

networks:
  ollama-docker:
    external: false